/*
 * File:           C:\ST\Project\HM50S-firmware\SStudio\HM50S_ADAU1761_PARAM.h
 *
 * Created:        Thursday, September 25, 2025 9:23:17 AM
 * Description:    HM50S:ADAU1761 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2025 Analog Devices, Inc. All rights reserved.
 */
#ifndef __HM50S_ADAU1761_PARAM_H__
#define __HM50S_ADAU1761_PARAM_H__


/* Module Modulo Size - Modulo Size*/
#define MOD_MODULOSIZE_COUNT                           1
#define MOD_MODULOSIZE_DEVICE                          "ADAU1761"
#define MOD_MODULOSIZE_MODULO_SIZE_ADDR                0
#define MOD_MODULOSIZE_MODULO_SIZE_FIXPT               0x00001000
#define MOD_MODULOSIZE_MODULO_SIZE_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(4096)
#define MOD_MODULOSIZE_MODULO_SIZE_TYPE                SIGMASTUDIOTYPE_INTEGER

/* Module H(t)2 - Hilbert Transform*/
#define MOD_HT2_COUNT                                  26
#define MOD_HT2_DEVICE                                 "ADAU1761"
#define MOD_HT2_ALG0_LOOP0_ADDR                        8
#define MOD_HT2_ALG0_LOOP0_FIXPT                       0xFF8014BC
#define MOD_HT2_ALG0_LOOP0_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99936731)
#define MOD_HT2_ALG0_LOOP0_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP1_ADDR                        9
#define MOD_HT2_ALG0_LOOP1_FIXPT                       0xFF802F78
#define MOD_HT2_ALG0_LOOP1_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99855144)
#define MOD_HT2_ALG0_LOOP1_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP2_ADDR                        10
#define MOD_HT2_ALG0_LOOP2_FIXPT                       0xFF80A1D3
#define MOD_HT2_ALG0_LOOP2_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99506157)
#define MOD_HT2_ALG0_LOOP2_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP3_ADDR                        11
#define MOD_HT2_ALG0_LOOP3_FIXPT                       0xFF81E65A
#define MOD_HT2_ALG0_LOOP3_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.98515781)
#define MOD_HT2_ALG0_LOOP3_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP4_ADDR                        12
#define MOD_HT2_ALG0_LOOP4_FIXPT                       0xFF856635
#define MOD_HT2_ALG0_LOOP4_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.95781849)
#define MOD_HT2_ALG0_LOOP4_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP5_ADDR                        13
#define MOD_HT2_ALG0_LOOP5_FIXPT                       0xFF8ED088
#define MOD_HT2_ALG0_LOOP5_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.88426115)
#define MOD_HT2_ALG0_LOOP5_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP6_ADDR                        14
#define MOD_HT2_ALG0_LOOP6_FIXPT                       0xFFA6989F
#define MOD_HT2_ALG0_LOOP6_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.69846748)
#define MOD_HT2_ALG0_LOOP6_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP7_ADDR                        15
#define MOD_HT2_ALG0_LOOP7_FIXPT                       0xFFAF6744
#define MOD_HT2_ALG0_LOOP7_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.62966114)
#define MOD_HT2_ALG0_LOOP7_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP8_ADDR                        16
#define MOD_HT2_ALG0_LOOP8_FIXPT                       0x0014B4B0
#define MOD_HT2_ALG0_LOOP8_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.16176415)
#define MOD_HT2_ALG0_LOOP8_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP9_ADDR                        17
#define MOD_HT2_ALG0_LOOP9_FIXPT                       0xFFE4B4B0
#define MOD_HT2_ALG0_LOOP9_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.21323591)
#define MOD_HT2_ALG0_LOOP9_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP10_ADDR                       18
#define MOD_HT2_ALG0_LOOP10_FIXPT                      0x001C2CD3
#define MOD_HT2_ALG0_LOOP10_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.22011802)
#define MOD_HT2_ALG0_LOOP10_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP11_ADDR                       19
#define MOD_HT2_ALG0_LOOP11_FIXPT                      0x003D335F
#define MOD_HT2_ALG0_LOOP11_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.47813033)
#define MOD_HT2_ALG0_LOOP11_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP12_ADDR                       20
#define MOD_HT2_ALG0_LOOP12_FIXPT                      0x002C2904
#define MOD_HT2_ALG0_LOOP12_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.34500173)
#define MOD_HT2_ALG0_LOOP12_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP13_ADDR                       21
#define MOD_HT2_ALG0_LOOP13_FIXPT                      0xFF802893
#define MOD_HT2_ALG0_LOOP13_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99876182)
#define MOD_HT2_ALG0_LOOP13_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP14_ADDR                       22
#define MOD_HT2_ALG0_LOOP14_FIXPT                      0xFF80551D
#define MOD_HT2_ALG0_LOOP14_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99740256)
#define MOD_HT2_ALG0_LOOP14_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP15_ADDR                       23
#define MOD_HT2_ALG0_LOOP15_FIXPT                      0xFF811C96
#define MOD_HT2_ALG0_LOOP15_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99131518)
#define MOD_HT2_ALG0_LOOP15_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP16_ADDR                       24
#define MOD_HT2_ALG0_LOOP16_FIXPT                      0xFF833676
#define MOD_HT2_ALG0_LOOP16_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.97490049)
#define MOD_HT2_ALG0_LOOP16_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP17_ADDR                       25
#define MOD_HT2_ALG0_LOOP17_FIXPT                      0xFF89002F
#define MOD_HT2_ALG0_LOOP17_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.92968192)
#define MOD_HT2_ALG0_LOOP17_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP18_ADDR                       26
#define MOD_HT2_ALG0_LOOP18_FIXPT                      0xFF9802D5
#define MOD_HT2_ALG0_LOOP18_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.8124136)
#define MOD_HT2_ALG0_LOOP18_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP19_ADDR                       27
#define MOD_HT2_ALG0_LOOP19_FIXPT                      0xFFC16A3B
#define MOD_HT2_ALG0_LOOP19_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.48894571)
#define MOD_HT2_ALG0_LOOP19_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP20_ADDR                       28
#define MOD_HT2_ALG0_LOOP20_FIXPT                      0xFFD491D0
#define MOD_HT2_ALG0_LOOP20_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.3393002)
#define MOD_HT2_ALG0_LOOP20_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP21_ADDR                       29
#define MOD_HT2_ALG0_LOOP21_FIXPT                      0x0012E705
#define MOD_HT2_ALG0_LOOP21_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.14767516)
#define MOD_HT2_ALG0_LOOP21_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP22_ADDR                       30
#define MOD_HT2_ALG0_LOOP22_FIXPT                      0x0009178D
#define MOD_HT2_ALG0_LOOP22_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.071031279)
#define MOD_HT2_ALG0_LOOP22_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP23_ADDR                       31
#define MOD_HT2_ALG0_LOOP23_FIXPT                      0x000B8614
#define MOD_HT2_ALG0_LOOP23_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.090029276)
#define MOD_HT2_ALG0_LOOP23_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP24_ADDR                       32
#define MOD_HT2_ALG0_LOOP24_FIXPT                      0x0040732A
#define MOD_HT2_ALG0_LOOP24_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.50351455)
#define MOD_HT2_ALG0_LOOP24_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT2_ALG0_LOOP25_ADDR                       33
#define MOD_HT2_ALG0_LOOP25_FIXPT                      0x001EE487
#define MOD_HT2_ALG0_LOOP25_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.24134918)
#define MOD_HT2_ALG0_LOOP25_TYPE                       SIGMASTUDIOTYPE_FIXPOINT

/* Module H(t)3 - Hilbert Transform*/
#define MOD_HT3_COUNT                                  26
#define MOD_HT3_DEVICE                                 "ADAU1761"
#define MOD_HT3_ALG0_LOOP0_ADDR                        34
#define MOD_HT3_ALG0_LOOP0_FIXPT                       0xFF8014BC
#define MOD_HT3_ALG0_LOOP0_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99936731)
#define MOD_HT3_ALG0_LOOP0_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP1_ADDR                        35
#define MOD_HT3_ALG0_LOOP1_FIXPT                       0xFF802F78
#define MOD_HT3_ALG0_LOOP1_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99855144)
#define MOD_HT3_ALG0_LOOP1_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP2_ADDR                        36
#define MOD_HT3_ALG0_LOOP2_FIXPT                       0xFF80A1D3
#define MOD_HT3_ALG0_LOOP2_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99506157)
#define MOD_HT3_ALG0_LOOP2_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP3_ADDR                        37
#define MOD_HT3_ALG0_LOOP3_FIXPT                       0xFF81E65A
#define MOD_HT3_ALG0_LOOP3_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.98515781)
#define MOD_HT3_ALG0_LOOP3_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP4_ADDR                        38
#define MOD_HT3_ALG0_LOOP4_FIXPT                       0xFF856635
#define MOD_HT3_ALG0_LOOP4_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.95781849)
#define MOD_HT3_ALG0_LOOP4_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP5_ADDR                        39
#define MOD_HT3_ALG0_LOOP5_FIXPT                       0xFF8ED088
#define MOD_HT3_ALG0_LOOP5_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.88426115)
#define MOD_HT3_ALG0_LOOP5_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP6_ADDR                        40
#define MOD_HT3_ALG0_LOOP6_FIXPT                       0xFFA6989F
#define MOD_HT3_ALG0_LOOP6_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.69846748)
#define MOD_HT3_ALG0_LOOP6_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP7_ADDR                        41
#define MOD_HT3_ALG0_LOOP7_FIXPT                       0xFFAF6744
#define MOD_HT3_ALG0_LOOP7_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.62966114)
#define MOD_HT3_ALG0_LOOP7_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP8_ADDR                        42
#define MOD_HT3_ALG0_LOOP8_FIXPT                       0x0014B4B0
#define MOD_HT3_ALG0_LOOP8_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.16176415)
#define MOD_HT3_ALG0_LOOP8_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP9_ADDR                        43
#define MOD_HT3_ALG0_LOOP9_FIXPT                       0xFFE4B4B0
#define MOD_HT3_ALG0_LOOP9_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.21323591)
#define MOD_HT3_ALG0_LOOP9_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP10_ADDR                       44
#define MOD_HT3_ALG0_LOOP10_FIXPT                      0x001C2CD3
#define MOD_HT3_ALG0_LOOP10_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.22011802)
#define MOD_HT3_ALG0_LOOP10_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP11_ADDR                       45
#define MOD_HT3_ALG0_LOOP11_FIXPT                      0x003D335F
#define MOD_HT3_ALG0_LOOP11_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.47813033)
#define MOD_HT3_ALG0_LOOP11_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP12_ADDR                       46
#define MOD_HT3_ALG0_LOOP12_FIXPT                      0x002C2904
#define MOD_HT3_ALG0_LOOP12_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.34500173)
#define MOD_HT3_ALG0_LOOP12_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP13_ADDR                       47
#define MOD_HT3_ALG0_LOOP13_FIXPT                      0xFF802893
#define MOD_HT3_ALG0_LOOP13_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99876182)
#define MOD_HT3_ALG0_LOOP13_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP14_ADDR                       48
#define MOD_HT3_ALG0_LOOP14_FIXPT                      0xFF80551D
#define MOD_HT3_ALG0_LOOP14_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99740256)
#define MOD_HT3_ALG0_LOOP14_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP15_ADDR                       49
#define MOD_HT3_ALG0_LOOP15_FIXPT                      0xFF811C96
#define MOD_HT3_ALG0_LOOP15_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99131518)
#define MOD_HT3_ALG0_LOOP15_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP16_ADDR                       50
#define MOD_HT3_ALG0_LOOP16_FIXPT                      0xFF833676
#define MOD_HT3_ALG0_LOOP16_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.97490049)
#define MOD_HT3_ALG0_LOOP16_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP17_ADDR                       51
#define MOD_HT3_ALG0_LOOP17_FIXPT                      0xFF89002F
#define MOD_HT3_ALG0_LOOP17_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.92968192)
#define MOD_HT3_ALG0_LOOP17_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP18_ADDR                       52
#define MOD_HT3_ALG0_LOOP18_FIXPT                      0xFF9802D5
#define MOD_HT3_ALG0_LOOP18_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.8124136)
#define MOD_HT3_ALG0_LOOP18_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP19_ADDR                       53
#define MOD_HT3_ALG0_LOOP19_FIXPT                      0xFFC16A3B
#define MOD_HT3_ALG0_LOOP19_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.48894571)
#define MOD_HT3_ALG0_LOOP19_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP20_ADDR                       54
#define MOD_HT3_ALG0_LOOP20_FIXPT                      0xFFD491D0
#define MOD_HT3_ALG0_LOOP20_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.3393002)
#define MOD_HT3_ALG0_LOOP20_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP21_ADDR                       55
#define MOD_HT3_ALG0_LOOP21_FIXPT                      0x0012E705
#define MOD_HT3_ALG0_LOOP21_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.14767516)
#define MOD_HT3_ALG0_LOOP21_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP22_ADDR                       56
#define MOD_HT3_ALG0_LOOP22_FIXPT                      0x0009178D
#define MOD_HT3_ALG0_LOOP22_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.071031279)
#define MOD_HT3_ALG0_LOOP22_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP23_ADDR                       57
#define MOD_HT3_ALG0_LOOP23_FIXPT                      0x000B8614
#define MOD_HT3_ALG0_LOOP23_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.090029276)
#define MOD_HT3_ALG0_LOOP23_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP24_ADDR                       58
#define MOD_HT3_ALG0_LOOP24_FIXPT                      0x0040732A
#define MOD_HT3_ALG0_LOOP24_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.50351455)
#define MOD_HT3_ALG0_LOOP24_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT3_ALG0_LOOP25_ADDR                       59
#define MOD_HT3_ALG0_LOOP25_FIXPT                      0x001EE487
#define MOD_HT3_ALG0_LOOP25_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.24134918)
#define MOD_HT3_ALG0_LOOP25_TYPE                       SIGMASTUDIOTYPE_FIXPOINT

/* Module H(t)1 - Hilbert Transform*/
#define MOD_HT1_COUNT                                  26
#define MOD_HT1_DEVICE                                 "ADAU1761"
#define MOD_HT1_ALG0_LOOP0_ADDR                        60
#define MOD_HT1_ALG0_LOOP0_FIXPT                       0xFF8014BC
#define MOD_HT1_ALG0_LOOP0_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99936731)
#define MOD_HT1_ALG0_LOOP0_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP1_ADDR                        61
#define MOD_HT1_ALG0_LOOP1_FIXPT                       0xFF802F78
#define MOD_HT1_ALG0_LOOP1_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99855144)
#define MOD_HT1_ALG0_LOOP1_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP2_ADDR                        62
#define MOD_HT1_ALG0_LOOP2_FIXPT                       0xFF80A1D3
#define MOD_HT1_ALG0_LOOP2_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99506157)
#define MOD_HT1_ALG0_LOOP2_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP3_ADDR                        63
#define MOD_HT1_ALG0_LOOP3_FIXPT                       0xFF81E65A
#define MOD_HT1_ALG0_LOOP3_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.98515781)
#define MOD_HT1_ALG0_LOOP3_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP4_ADDR                        64
#define MOD_HT1_ALG0_LOOP4_FIXPT                       0xFF856635
#define MOD_HT1_ALG0_LOOP4_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.95781849)
#define MOD_HT1_ALG0_LOOP4_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP5_ADDR                        65
#define MOD_HT1_ALG0_LOOP5_FIXPT                       0xFF8ED088
#define MOD_HT1_ALG0_LOOP5_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.88426115)
#define MOD_HT1_ALG0_LOOP5_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP6_ADDR                        66
#define MOD_HT1_ALG0_LOOP6_FIXPT                       0xFFA6989F
#define MOD_HT1_ALG0_LOOP6_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.69846748)
#define MOD_HT1_ALG0_LOOP6_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP7_ADDR                        67
#define MOD_HT1_ALG0_LOOP7_FIXPT                       0xFFAF6744
#define MOD_HT1_ALG0_LOOP7_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.62966114)
#define MOD_HT1_ALG0_LOOP7_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP8_ADDR                        68
#define MOD_HT1_ALG0_LOOP8_FIXPT                       0x0014B4B0
#define MOD_HT1_ALG0_LOOP8_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.16176415)
#define MOD_HT1_ALG0_LOOP8_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP9_ADDR                        69
#define MOD_HT1_ALG0_LOOP9_FIXPT                       0xFFE4B4B0
#define MOD_HT1_ALG0_LOOP9_VALUE                       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.21323591)
#define MOD_HT1_ALG0_LOOP9_TYPE                        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP10_ADDR                       70
#define MOD_HT1_ALG0_LOOP10_FIXPT                      0x001C2CD3
#define MOD_HT1_ALG0_LOOP10_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.22011802)
#define MOD_HT1_ALG0_LOOP10_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP11_ADDR                       71
#define MOD_HT1_ALG0_LOOP11_FIXPT                      0x003D335F
#define MOD_HT1_ALG0_LOOP11_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.47813033)
#define MOD_HT1_ALG0_LOOP11_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP12_ADDR                       72
#define MOD_HT1_ALG0_LOOP12_FIXPT                      0x002C2904
#define MOD_HT1_ALG0_LOOP12_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.34500173)
#define MOD_HT1_ALG0_LOOP12_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP13_ADDR                       73
#define MOD_HT1_ALG0_LOOP13_FIXPT                      0xFF802893
#define MOD_HT1_ALG0_LOOP13_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99876182)
#define MOD_HT1_ALG0_LOOP13_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP14_ADDR                       74
#define MOD_HT1_ALG0_LOOP14_FIXPT                      0xFF80551D
#define MOD_HT1_ALG0_LOOP14_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99740256)
#define MOD_HT1_ALG0_LOOP14_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP15_ADDR                       75
#define MOD_HT1_ALG0_LOOP15_FIXPT                      0xFF811C96
#define MOD_HT1_ALG0_LOOP15_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.99131518)
#define MOD_HT1_ALG0_LOOP15_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP16_ADDR                       76
#define MOD_HT1_ALG0_LOOP16_FIXPT                      0xFF833676
#define MOD_HT1_ALG0_LOOP16_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.97490049)
#define MOD_HT1_ALG0_LOOP16_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP17_ADDR                       77
#define MOD_HT1_ALG0_LOOP17_FIXPT                      0xFF89002F
#define MOD_HT1_ALG0_LOOP17_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.92968192)
#define MOD_HT1_ALG0_LOOP17_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP18_ADDR                       78
#define MOD_HT1_ALG0_LOOP18_FIXPT                      0xFF9802D5
#define MOD_HT1_ALG0_LOOP18_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.8124136)
#define MOD_HT1_ALG0_LOOP18_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP19_ADDR                       79
#define MOD_HT1_ALG0_LOOP19_FIXPT                      0xFFC16A3B
#define MOD_HT1_ALG0_LOOP19_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.48894571)
#define MOD_HT1_ALG0_LOOP19_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP20_ADDR                       80
#define MOD_HT1_ALG0_LOOP20_FIXPT                      0xFFD491D0
#define MOD_HT1_ALG0_LOOP20_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.3393002)
#define MOD_HT1_ALG0_LOOP20_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP21_ADDR                       81
#define MOD_HT1_ALG0_LOOP21_FIXPT                      0x0012E705
#define MOD_HT1_ALG0_LOOP21_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.14767516)
#define MOD_HT1_ALG0_LOOP21_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP22_ADDR                       82
#define MOD_HT1_ALG0_LOOP22_FIXPT                      0x0009178D
#define MOD_HT1_ALG0_LOOP22_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.071031279)
#define MOD_HT1_ALG0_LOOP22_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP23_ADDR                       83
#define MOD_HT1_ALG0_LOOP23_FIXPT                      0x000B8614
#define MOD_HT1_ALG0_LOOP23_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.090029276)
#define MOD_HT1_ALG0_LOOP23_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP24_ADDR                       84
#define MOD_HT1_ALG0_LOOP24_FIXPT                      0x0040732A
#define MOD_HT1_ALG0_LOOP24_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.50351455)
#define MOD_HT1_ALG0_LOOP24_TYPE                       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_HT1_ALG0_LOOP25_ADDR                       85
#define MOD_HT1_ALG0_LOOP25_FIXPT                      0x001EE487
#define MOD_HT1_ALG0_LOOP25_VALUE                      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.24134918)
#define MOD_HT1_ALG0_LOOP25_TYPE                       SIGMASTUDIOTYPE_FIXPOINT

/* Module S Splitter1 - Single Control Splitter*/
#define MOD_SSPLITTER1_COUNT                           1
#define MOD_SSPLITTER1_DEVICE                          "ADAU1761"
#define MOD_SSPLITTER1_SINGLECTRLSPLIT1_ADDR           86
#define MOD_SSPLITTER1_SINGLECTRLSPLIT1_FIXPT          0x004026E7
#define MOD_SSPLITTER1_SINGLECTRLSPLIT1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.501187233627272)
#define MOD_SSPLITTER1_SINGLECTRLSPLIT1_TYPE           SIGMASTUDIOTYPE_FIXPOINT

/* Module S Splitter2 - Single Control Splitter*/
#define MOD_SSPLITTER2_COUNT                           1
#define MOD_SSPLITTER2_DEVICE                          "ADAU1761"
#define MOD_SSPLITTER2_SINGLECTRLSPLIT2_ADDR           87
#define MOD_SSPLITTER2_SINGLECTRLSPLIT2_FIXPT          0x004026E7
#define MOD_SSPLITTER2_SINGLECTRLSPLIT2_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.501187233627272)
#define MOD_SSPLITTER2_SINGLECTRLSPLIT2_TYPE           SIGMASTUDIOTYPE_FIXPOINT

#endif
